# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.dbui_v1alpha1_autoloader_preview_response import DbuiV1alpha1AutoloaderPreviewResponse

class TestDbuiV1alpha1AutoloaderPreviewResponse(unittest.TestCase):
    """DbuiV1alpha1AutoloaderPreviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DbuiV1alpha1AutoloaderPreviewResponse:
        """Test DbuiV1alpha1AutoloaderPreviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DbuiV1alpha1AutoloaderPreviewResponse`
        """
        model = DbuiV1alpha1AutoloaderPreviewResponse()
        if include_optional:
            return DbuiV1alpha1AutoloaderPreviewResponse(
                columns = [
                    dasl_api.models.dbui/v1alpha1/table_column_details.dbui.v1alpha1.TableColumnDetails(
                        name = '', 
                        type_name = '', 
                        type_detail = '', 
                        position = 56, 
                        nullable = True, )
                    ],
                data = [
                    {
                        'key' : ''
                        }
                    ]
            )
        else:
            return DbuiV1alpha1AutoloaderPreviewResponse(
        )
        """

    def testDbuiV1alpha1AutoloaderPreviewResponse(self):
        """Test DbuiV1alpha1AutoloaderPreviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
