# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.dbui_v1alpha1_dismiss_operational_alerts_request import DbuiV1alpha1DismissOperationalAlertsRequest

class TestDbuiV1alpha1DismissOperationalAlertsRequest(unittest.TestCase):
    """DbuiV1alpha1DismissOperationalAlertsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DbuiV1alpha1DismissOperationalAlertsRequest:
        """Test DbuiV1alpha1DismissOperationalAlertsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DbuiV1alpha1DismissOperationalAlertsRequest`
        """
        model = DbuiV1alpha1DismissOperationalAlertsRequest()
        if include_optional:
            return DbuiV1alpha1DismissOperationalAlertsRequest(
                warehouse = '',
                ids = [
                    ''
                    ]
            )
        else:
            return DbuiV1alpha1DismissOperationalAlertsRequest(
        )
        """

    def testDbuiV1alpha1DismissOperationalAlertsRequest(self):
        """Test DbuiV1alpha1DismissOperationalAlertsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
