# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.core_v1alpha1_data_source_field_utils_unreferenced_columns import CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns

class TestCoreV1alpha1DataSourceFieldUtilsUnreferencedColumns(unittest.TestCase):
    """CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns:
        """Test CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns`
        """
        model = CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns()
        if include_optional:
            return CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns(
                preserve = True,
                embed_column = '',
                omit_columns = [
                    ''
                    ],
                duplicate_prefix = ''
            )
        else:
            return CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns(
        )
        """

    def testCoreV1alpha1DataSourceFieldUtilsUnreferencedColumns(self):
        """Test CoreV1alpha1DataSourceFieldUtilsUnreferencedColumns"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
