# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.dbui_v1alpha1_transform_request_transforms_inner_preset_overrides import DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides

class TestDbuiV1alpha1TransformRequestTransformsInnerPresetOverrides(unittest.TestCase):
    """DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides:
        """Test DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides`
        """
        model = DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides()
        if include_optional:
            return DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides(
                omit_fields = [
                    ''
                    ]
            )
        else:
            return DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides(
        )
        """

    def testDbuiV1alpha1TransformRequestTransformsInnerPresetOverrides(self):
        """Test DbuiV1alpha1TransformRequestTransformsInnerPresetOverrides"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
