# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.content_v1alpha1_datasource_preset_list_recommended_presets_inner import ContentV1alpha1DatasourcePresetListRecommendedPresetsInner

class TestContentV1alpha1DatasourcePresetListRecommendedPresetsInner(unittest.TestCase):
    """ContentV1alpha1DatasourcePresetListRecommendedPresetsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV1alpha1DatasourcePresetListRecommendedPresetsInner:
        """Test ContentV1alpha1DatasourcePresetListRecommendedPresetsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV1alpha1DatasourcePresetListRecommendedPresetsInner`
        """
        model = ContentV1alpha1DatasourcePresetListRecommendedPresetsInner()
        if include_optional:
            return ContentV1alpha1DatasourcePresetListRecommendedPresetsInner(
                name = '',
                author = '',
                description = ''
            )
        else:
            return ContentV1alpha1DatasourcePresetListRecommendedPresetsInner(
        )
        """

    def testContentV1alpha1DatasourcePresetListRecommendedPresetsInner(self):
        """Test ContentV1alpha1DatasourcePresetListRecommendedPresetsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
