# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.dbui_v1alpha1_operational_alert_summary import DbuiV1alpha1OperationalAlertSummary

class TestDbuiV1alpha1OperationalAlertSummary(unittest.TestCase):
    """DbuiV1alpha1OperationalAlertSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DbuiV1alpha1OperationalAlertSummary:
        """Test DbuiV1alpha1OperationalAlertSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DbuiV1alpha1OperationalAlertSummary`
        """
        model = DbuiV1alpha1OperationalAlertSummary()
        if include_optional:
            return DbuiV1alpha1OperationalAlertSummary(
                currently_open = 1.337,
                alerts_last7days = 1.337,
                alerts_preceding7days = 1.337,
                alerts_last24hours = 1.337,
                alerts_preceding24hours = 1.337,
                alerts_spark_line = [
                    1.337
                    ]
            )
        else:
            return DbuiV1alpha1OperationalAlertSummary(
                currently_open = 1.337,
                alerts_last7days = 1.337,
                alerts_preceding7days = 1.337,
                alerts_last24hours = 1.337,
                alerts_preceding24hours = 1.337,
                alerts_spark_line = [
                    1.337
                    ],
        )
        """

    def testDbuiV1alpha1OperationalAlertSummary(self):
        """Test DbuiV1alpha1OperationalAlertSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
