# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.dbui_v1alpha1_autoloader_preview_request import DbuiV1alpha1AutoloaderPreviewRequest

class TestDbuiV1alpha1AutoloaderPreviewRequest(unittest.TestCase):
    """DbuiV1alpha1AutoloaderPreviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DbuiV1alpha1AutoloaderPreviewRequest:
        """Test DbuiV1alpha1AutoloaderPreviewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DbuiV1alpha1AutoloaderPreviewRequest`
        """
        model = DbuiV1alpha1AutoloaderPreviewRequest()
        if include_optional:
            return DbuiV1alpha1AutoloaderPreviewRequest(
                warehouse = '',
                autoloader = dasl_api.models.core/v1alpha1/data_source_autoloader_spec.core.v1alpha1.DataSourceAutoloaderSpec(
                    format = '', 
                    location = '', 
                    schema_file = '', 
                    cloud_files = dasl_api.models.content_v1alpha1_datasource_preset_autoloader_cloud_files.content_v1alpha1_DatasourcePreset_autoloader_cloudFiles(
                        schema_hints_file = '', 
                        schema_hints = '', ), ),
                page_size = 56,
                page = 56
            )
        else:
            return DbuiV1alpha1AutoloaderPreviewRequest(
                warehouse = '',
                autoloader = dasl_api.models.core/v1alpha1/data_source_autoloader_spec.core.v1alpha1.DataSourceAutoloaderSpec(
                    format = '', 
                    location = '', 
                    schema_file = '', 
                    cloud_files = dasl_api.models.content_v1alpha1_datasource_preset_autoloader_cloud_files.content_v1alpha1_DatasourcePreset_autoloader_cloudFiles(
                        schema_hints_file = '', 
                        schema_hints = '', ), ),
        )
        """

    def testDbuiV1alpha1AutoloaderPreviewRequest(self):
        """Test DbuiV1alpha1AutoloaderPreviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
