# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.workspace_v1alpha1_workspace_config_spec_observables import WorkspaceV1alpha1WorkspaceConfigSpecObservables

class TestWorkspaceV1alpha1WorkspaceConfigSpecObservables(unittest.TestCase):
    """WorkspaceV1alpha1WorkspaceConfigSpecObservables unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceV1alpha1WorkspaceConfigSpecObservables:
        """Test WorkspaceV1alpha1WorkspaceConfigSpecObservables
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceV1alpha1WorkspaceConfigSpecObservables`
        """
        model = WorkspaceV1alpha1WorkspaceConfigSpecObservables()
        if include_optional:
            return WorkspaceV1alpha1WorkspaceConfigSpecObservables(
                kinds = [
                    dasl_api.models.workspace_v1alpha1_workspace_config_spec_observables_kinds_inner.workspace_v1alpha1_WorkspaceConfigSpec_observables_kinds_inner(
                        name = '', 
                        sql_type = '', )
                    ],
                relationships = [
                    ''
                    ]
            )
        else:
            return WorkspaceV1alpha1WorkspaceConfigSpecObservables(
        )
        """

    def testWorkspaceV1alpha1WorkspaceConfigSpecObservables(self):
        """Test WorkspaceV1alpha1WorkspaceConfigSpecObservables"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
