# coding: utf-8

"""
    Antimatter Security Lakehouse Public API

    Interact with the Antimatter ASL API.

    The version of the OpenAPI document: 0.0.12
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.dbui_v1alpha1_promote_event_request import DbuiV1alpha1PromoteEventRequest

class TestDbuiV1alpha1PromoteEventRequest(unittest.TestCase):
    """DbuiV1alpha1PromoteEventRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DbuiV1alpha1PromoteEventRequest:
        """Test DbuiV1alpha1PromoteEventRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DbuiV1alpha1PromoteEventRequest`
        """
        model = DbuiV1alpha1PromoteEventRequest()
        if include_optional:
            return DbuiV1alpha1PromoteEventRequest(
                summary = '',
                context = {
                    'key' : ''
                    },
                state = 'Open',
                assigned_to = '',
                observables = [
                    dasl_api.models.dbui/v1alpha1/observable_instance.dbui.v1alpha1.ObservableInstance(
                        kind = '', 
                        value = '', 
                        relationship = '', 
                        risk = dasl_api.models.dbui_v1alpha1_observable_instance_risk.dbui_v1alpha1_ObservableInstance_risk(
                            notable_impact = 1.337, 
                            notable_confidence = 1.337, 
                            score_last24h = 1.337, 
                            total_score = 1.337, ), )
                    ]
            )
        else:
            return DbuiV1alpha1PromoteEventRequest(
        )
        """

    def testDbuiV1alpha1PromoteEventRequest(self):
        """Test DbuiV1alpha1PromoteEventRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
