GEMINI_2_0_FLASH_EXPERIMENTAL = "gemini/gemini-2.0-flash-exp"
OPENAI_GPT_4O_MINI = "gpt-4o-mini"
GROQ_LLAMA_3_3_70B_SPECDEC = "groq/llama-3.3-70b-specdec"
GROQ_LLAMA_3_3_70B_VERSATILE = "groq/llama-3.3-70b-versatile"

DEEPSEEK_DEEPSEEK_V3 = "deepseek/deepseek-chat"
DEEPSEEK_DEEPSEEK_REASONER = "deepseek/deepseek-reasoner"

OPENAI_O1_MINI = "o1-mini"
OPENAI_O1 = "o1"

ANTHROPIC_CLAUDE_3_5_SONNET = "anthropic/claude-3-5-sonnet-20241022"
ANTHROPIC_CLAUDE_3_5_HAIKU = "anthropic/claude-3-5-haiku-20241022"

OPENAI_GPT_4O = "gpt-4o"
OPENAI_O3_MINI = "o3-mini"

TESTING_MODEL = OPENAI_O3_MINI
# TESTING_MODEL = GEMINI_2_0_FLASH_EXPERIMENTAL
DEFAULT_MAIN_MODEL = OPENAI_O3_MINI
DEFAULT_EDITOR_MODEL = ANTHROPIC_CLAUDE_3_5_SONNET
DEFAULT_EVALUATOR_MODEL = OPENAI_O3_MINI
