# Generated by Django 4.2.17 on 2025-02-23 20:56

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bothelpers", "0002_alter_link_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (("it_commands", "Can use IT commands"),),
            },
        ),
        migrations.AlterModelOptions(
            name="link",
            options={"verbose_name": "Link", "verbose_name_plural": "Links"},
        ),
        migrations.RemoveField(
            model_name="link",
            name="auth",
        ),
        migrations.AddField(
            model_name="link",
            name="type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General Link"),
                    ("AUTH", "Alliance Auth Link"),
                    ("INTEL", "Intel Link"),
                ],
                default="GENERAL",
                help_text="Type of link",
                max_length=20,
            ),
        ),
    ]
