
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-24T19:21:47+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "95bd24f532425163ae19b777c49467dc0489c913",
 "version": "0.0.55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
