
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-24T18:22:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "67017a662a65abaa0e388925762aa3c903abe840",
 "version": "2.28.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
