# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mtm/sppb/cli.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'mtm/sppb/cli.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mtm/sppb/cli.proto\x12\x04sppb\"P\n\x0e\x43liCommandItem\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n\x07\x63mdLine\x18\x02 \x01(\tR\x07\x63mdLine\x12\x14\n\x05label\x18\x03 \x01(\tR\x05label\"\x0c\n\nListCliReq\"N\n\nListCliRes\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x14.sppb.CliCommandItemR\x05items\x12\x14\n\x05\x63ount\x18\x02 \x01(\rR\x05\x63ount2K\n\x0cMtCliService\x12;\n\x13\x43liCommandTemplates\x12\x10.sppb.ListCliReq\x1a\x10.sppb.ListCliRes\"\x00\x42m\n\x08\x63om.sppbB\x08\x43liProtoP\x01Z\'github.com/codeh007/gomtm/mtm/sppb;sppb\xa2\x02\x03SXX\xaa\x02\x04Sppb\xca\x02\x04Sppb\xe2\x02\x10Sppb\\GPBMetadata\xea\x02\x04Sppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mtm.sppb.cli_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\010com.sppbB\010CliProtoP\001Z\'github.com/codeh007/gomtm/mtm/sppb;sppb\242\002\003SXX\252\002\004Sppb\312\002\004Sppb\342\002\020Sppb\\GPBMetadata\352\002\004Sppb'
  _globals['_CLICOMMANDITEM']._serialized_start=28
  _globals['_CLICOMMANDITEM']._serialized_end=108
  _globals['_LISTCLIREQ']._serialized_start=110
  _globals['_LISTCLIREQ']._serialized_end=122
  _globals['_LISTCLIRES']._serialized_start=124
  _globals['_LISTCLIRES']._serialized_end=202
  _globals['_MTCLISERVICE']._serialized_start=204
  _globals['_MTCLISERVICE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
