import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_0ecc87b26d(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_08bba9c44b():spartaqube_cli.list()
@app.command()
def sparta_4b65405ec6():spartaqube_cli.sparta_4b65405ec6()
@app.command()
def sparta_c7ce93660a():print('Hello world!')
if __name__=='__main__':app()