
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-23T20:15:05+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c039db7b057ce507d0f19470dfb794f0fa3a8037",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
