
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-25T11:38:40-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "41e1e516e9f4b7de07f96e7a3e7f8d5e2d118057",
 "version": "v0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
