
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-23T17:07:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "46b4d965dc14de1a8b0ae04e11035ab0644cadd1",
 "version": "2025.2.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
