# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: colav_proto/missionRequest.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n colav_proto/missionRequest.proto\x12\x05\x63olav\"\xf6\x06\n\x0eMissionRequest\x12\x0b\n\x03tag\x18\x01 \x02(\t\x12\x1f\n\x17mission_start_timestamp\x18\x02 \x02(\t\x12,\n\x06vessel\x18\x03 \x02(\x0b\x32\x1c.colav.MissionRequest.Vessel\x12:\n\x15mission_init_position\x18\x04 \x02(\x0b\x32\x1b.colav.MissionRequest.Point\x12:\n\x15mission_goal_position\x18\x05 \x02(\x0b\x32\x1b.colav.MissionRequest.Point\x12&\n\x1emission_goal_acceptance_radius\x18\x06 \x02(\x02\x1a(\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\xbd\x04\n\x06Vessel\x12\x0b\n\x03tag\x18\x01 \x02(\t\x12\x42\n\x04type\x18\x02 \x02(\x0e\x32\'.colav.MissionRequest.Vessel.VesselType:\x0bUNSPECIFIED\x12J\n\x12vessel_constraints\x18\x03 \x02(\x0b\x32..colav.MissionRequest.Vessel.VesselConstraints\x12\x44\n\x0fvessel_geometry\x18\x04 \x02(\x0b\x32+.colav.MissionRequest.Vessel.VesselGeometry\x1a\xb3\x01\n\x11VesselConstraints\x12\x18\n\x10max_acceleration\x18\x03 \x02(\x02\x12\x18\n\x10max_deceleration\x18\x04 \x02(\x02\x12\x14\n\x0cmax_velocity\x18\x05 \x02(\x02\x12\x14\n\x0cmin_velocity\x18\x06 \x02(\x02\x12\x14\n\x0cmax_yaw_rate\x18\x07 \x02(\x02\x1a(\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\x12\t\n\x01z\x18\x03 \x02(\x02\x1a\x61\n\x0eVesselGeometry\x12\x18\n\x10safety_threshold\x18\x01 \x01(\x02\x12\x35\n\x10polyshape_points\x18\x02 \x03(\x0b\x32\x1b.colav.MissionRequest.Point\"7\n\nVesselType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\r\n\tHYDROFOIL\x10\x01\x12\t\n\x05OTHER\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'colav_proto.missionRequest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MISSIONREQUEST']._serialized_start=44
  _globals['_MISSIONREQUEST']._serialized_end=930
  _globals['_MISSIONREQUEST_POINT']._serialized_start=314
  _globals['_MISSIONREQUEST_POINT']._serialized_end=354
  _globals['_MISSIONREQUEST_VESSEL']._serialized_start=357
  _globals['_MISSIONREQUEST_VESSEL']._serialized_end=930
  _globals['_MISSIONREQUEST_VESSEL_VESSELCONSTRAINTS']._serialized_start=595
  _globals['_MISSIONREQUEST_VESSEL_VESSELCONSTRAINTS']._serialized_end=774
  _globals['_MISSIONREQUEST_VESSEL_VESSELCONSTRAINTS_POINT']._serialized_start=734
  _globals['_MISSIONREQUEST_VESSEL_VESSELCONSTRAINTS_POINT']._serialized_end=774
  _globals['_MISSIONREQUEST_VESSEL_VESSELGEOMETRY']._serialized_start=776
  _globals['_MISSIONREQUEST_VESSEL_VESSELGEOMETRY']._serialized_end=873
  _globals['_MISSIONREQUEST_VESSEL_VESSELTYPE']._serialized_start=875
  _globals['_MISSIONREQUEST_VESSEL_VESSELTYPE']._serialized_end=930
# @@protoc_insertion_point(module_scope)
