PACKAGE_NAME = "graphrag_tagger"
VERSION = "0.1.1"
DESCRIPTION = "A lightweight toolkit for extracting topics from PDFs and visualizing their connections using graphs."
AUTHOR = "Alex Kameni"
AUTHOR_EMAIL = "kamenialexnea@gmail.com"
URL = "https://github.com/KameniAlexNea/graphrag-tagger"
