# Generated by Django 5.1.6 on 2025-02-22 05:15

import storages.backends.s3
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image_url', models.FileField(db_column='image_url', max_length=1024, storage=storages.backends.s3.S3Storage(access_key=None, bucket_name=None, endpoint_url='https://None', secret_key=None), upload_to='')),
                ('file_path', models.TextField(max_length=1024, null=True)),
                ('file_type', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('ref_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(max_length=250, null=True)),
                ('original_file_name', models.CharField(max_length=255, null=True)),
                ('file_size', models.CharField(max_length=250, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('storage_provider', models.CharField(blank=True, choices=[('local', 'Local'), ('s3', 'S3')], default='s3', max_length=64, null=True)),
                ('upload_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=64, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_uid', models.IntegerField(blank=True, editable=False, null=True)),
                ('write_uid', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
