# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima-sdk.models.get_people_list200_response_data_inner_employments_inner_team import GetPeopleList200ResponseDataInnerEmploymentsInnerTeam

class TestGetPeopleList200ResponseDataInnerEmploymentsInnerTeam(unittest.TestCase):
    """GetPeopleList200ResponseDataInnerEmploymentsInnerTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPeopleList200ResponseDataInnerEmploymentsInnerTeam:
        """Test GetPeopleList200ResponseDataInnerEmploymentsInnerTeam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPeopleList200ResponseDataInnerEmploymentsInnerTeam`
        """
        model = GetPeopleList200ResponseDataInnerEmploymentsInnerTeam()
        if include_optional:
            return GetPeopleList200ResponseDataInnerEmploymentsInnerTeam(
                id = '00000000-0000-0000-0000-000000000000',
                name = ''
            )
        else:
            return GetPeopleList200ResponseDataInnerEmploymentsInnerTeam(
        )
        """

    def testGetPeopleList200ResponseDataInnerEmploymentsInnerTeam(self):
        """Test GetPeopleList200ResponseDataInnerEmploymentsInnerTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
