countries_data=[
    {'name': 'Afghanistan', 'code': '93', 'iso': 'AF / AFG', 'flag': '🇦🇫'},
    {'name': 'Albania', 'code': '355', 'iso': 'AL / ALB', 'flag': '🇦🇱'},
    {'name': 'Algeria', 'code': '213', 'iso': 'DZ / DZA', 'flag': '🇩🇿'},
    {'name': 'American Samoa', 'code': '1', 'iso': 'AS / ASM', 'flag': '🇦🇸'},
    {'name': 'Andorra', 'code': '376', 'iso': 'AD / AND', 'flag': '🇦🇩'},
    {'name': 'Angola', 'code': '244', 'iso': 'AO / AGO', 'flag': '🇦🇴'},
    {'name': 'Anguilla', 'code': '1', 'iso': 'AI / AIA', 'flag': '🇦🇮'},
    {'name': 'Antarctica', 'code': '672', 'iso': 'AQ / ATA', 'flag': '🇦🇶'},
    {'name': 'Antigua and Barbuda', 'code': '1', 'iso': 'AG / ATG', 'flag': '🇦🇬'},
    {'name': 'Argentina', 'code': '54', 'iso': 'AR / ARG', 'flag': '🇦🇷'},
    {'name': 'Armenia', 'code': '374', 'iso': 'AM / ARM', 'flag': '🇦🇲'},
    {'name': 'Aruba', 'code': '297', 'iso': 'AW / ABW', 'flag': '🇦🇼'},
    {'name': 'Australia', 'code': '61', 'iso': 'AU / AUS', 'flag': '🇦🇺'},
    {'name': 'Austria', 'code': '43', 'iso': 'AT / AUT', 'flag': '🇦🇹'},
    {'name': 'Azerbaijan', 'code': '994', 'iso': 'AZ / AZE', 'flag': '🇦🇿'},
    {'name': 'Bahamas', 'code': '1', 'iso': 'BS / BHS', 'flag': '🇧🇸'},
    {'name': 'Bahrain', 'code': '973', 'iso': 'BH / BHR', 'flag': '🇧🇭'},
    {'name': 'Bangladesh', 'code': '880', 'iso': 'BD / BGD', 'flag': '🇧🇩'},
    {'name': 'Barbados', 'code': '1', 'iso': 'BB / BRB', 'flag': '🇧🇧'},
    {'name': 'Belarus', 'code': '375', 'iso': 'BY / BLR', 'flag': '🇧🇾'},
    {'name': 'Belgium', 'code': '32', 'iso': 'BE / BEL', 'flag': '🇧🇪'},
    {'name': 'Belize', 'code': '501', 'iso': 'BZ / BLZ', 'flag': '🇧🇿'},
    {'name': 'Benin', 'code': '229', 'iso': 'BJ / BEN', 'flag': '🇧🇯'},
    {'name': 'Bermuda', 'code': '1', 'iso': 'BM / BMU', 'flag': '🇧🇲'},
    {'name': 'Bhutan', 'code': '975', 'iso': 'BT / BTN', 'flag': '🇧🇹'},
    {'name': 'Bolivia', 'code': '591', 'iso': 'BO / BOL', 'flag': '🇧🇴'},
    {'name': 'Bosnia and Herzegovina', 'code': '387', 'iso': 'BA / BIH', 'flag': '🇧🇦'},
    {'name': 'Botswana', 'code': '267', 'iso': 'BW / BWA', 'flag': '🇧🇼'},
    {'name': 'Brazil', 'code': '55', 'iso': 'BR / BRA', 'flag': '🇧🇷'},
    {'name': 'British Indian Ocean Territory', 'code': '246', 'iso': 'IO / IOT', 'flag': '🇮🇴'},
    {'name': 'British Virgin Islands', 'code': '1', 'iso': 'VG / VGB', 'flag': '🇻🇬'},
    {'name': 'Brunei', 'code': '673', 'iso': 'BN / BRN', 'flag': '🇧🇳'},
    {'name': 'Bulgaria', 'code': '359', 'iso': 'BG / BGR', 'flag': '🇧🇬'},
    {'name': 'Burkina Faso', 'code': '226', 'iso': 'BF / BFA', 'flag': '🇧🇫'},
    {'name': 'Burundi', 'code': '257', 'iso': 'BI / BDI', 'flag': '🇧🇮'},
    {'name': 'Cambodia', 'code': '855', 'iso': 'KH / KHM', 'flag': '🇰🇭'},
    {'name': 'Cameroon', 'code': '237', 'iso': 'CM / CMR', 'flag': '🇨🇲'},
    {'name': 'Canada', 'code': '1', 'iso': 'CA / CAN', 'flag': '🇨🇦'},
    {'name': 'Cape Verde', 'code': '238', 'iso': 'CV / CPV', 'flag': '🇨🇻'},
    {'name': 'Cayman Islands', 'code': '1', 'iso': 'KY / CYM', 'flag': '🇰🇾'},
    {'name': 'Central African Republic', 'code': '236', 'iso': 'CF / CAF', 'flag': '🇨🇫'},
    {'name': 'Chad', 'code': '235', 'iso': 'TD / TCD', 'flag': '🇹🇩'},
    {'name': 'Chile', 'code': '56', 'iso': 'CL / CHL', 'flag': '🇨🇱'},
    {'name': 'China', 'code': '86', 'iso': 'CN / CHN', 'flag': '🇨🇳'},
    {'name': 'Christmas Island', 'code': '61', 'iso': 'CX / CXR', 'flag': '🇨🇽'},
    {'name': 'Cocos Islands', 'code': '61', 'iso': 'CC / CCK', 'flag': '🇨🇨'},
    {'name': 'Colombia', 'code': '57', 'iso': 'CO / COL', 'flag': '🇨🇴'},
    {'name': 'Comoros', 'code': '269', 'iso': 'KM / COM', 'flag': '🇰🇲'},
    {'name': 'Cook Islands', 'code': '682', 'iso': 'CK / COK', 'flag': '🇨🇰'},
    {'name': 'Costa Rica', 'code': '506', 'iso': 'CR / CRI', 'flag': '🇨🇷'},
    {'name': 'Croatia', 'code': '385', 'iso': 'HR / HRV', 'flag': '🇭🇷'},
    {'name': 'Cuba', 'code': '53', 'iso': 'CU / CUB', 'flag': '🇨🇺'},
    {'name': 'Curacao', 'code': '599', 'iso': 'CW / CUW', 'flag': '🇨🇼'},
    {'name': 'Cyprus', 'code': '357', 'iso': 'CY / CYP', 'flag': '🇨🇾'},
    {'name': 'Czech Republic', 'code': '420', 'iso': 'CZ / CZE', 'flag': '🇨🇿'},
    {'name': 'Democratic Republic of the Congo', 'code': '243', 'iso': 'CD / COD', 'flag': '🇨🇩'},
    {'name': 'Denmark', 'code': '45', 'iso': 'DK / DNK', 'flag': '🇩🇰'},
    {'name': 'Djibouti', 'code': '253', 'iso': 'DJ / DJI', 'flag': '🇩🇯'},
    {'name': 'Dominica', 'code': '1', 'iso': 'DM / DMA', 'flag': '🇩🇲'},
    {'name': 'Dominican Republic', 'code': '1', 'iso': 'DO / DOM', 'flag': '🇩🇴'},
    {'name': 'East Timor', 'code': '670', 'iso': 'TL / TLS', 'flag': '🇹🇱'},
    {'name': 'Ecuador', 'code': '593', 'iso': 'EC / ECU', 'flag': '🇪🇨'},
    {'name': 'Egypt', 'code': '20', 'iso': 'EG / EGY', 'flag': '🇪🇬'},
    {'name': 'El Salvador', 'code': '503', 'iso': 'SV / SLV', 'flag': '🇸🇻'},
    {'name': 'Equatorial Guinea', 'code': '240', 'iso': 'GQ / GNQ', 'flag': '🇬🇶'},
    {'name': 'Eritrea', 'code': '291', 'iso': 'ER / ERI', 'flag': '🇪🇷'},
    {'name': 'Estonia', 'code': '372', 'iso': 'EE / EST', 'flag': '🇪🇪'},
    {'name': 'Ethiopia', 'code': '251', 'iso': 'ET / ETH', 'flag': '🇪🇹'},
    {'name': 'Falkland Islands', 'code': '500', 'iso': 'FK / FLK', 'flag': '🇫🇰'},
    {'name': 'Faroe Islands', 'code': '298', 'iso': 'FO / FRO', 'flag': '🇫🇴'},
    {'name': 'Fiji', 'code': '679', 'iso': 'FJ / FJI', 'flag': '🇫🇯'},
    {'name': 'Finland', 'code': '358', 'iso': 'FI / FIN', 'flag': '🇫🇮'},
    {'name': 'France', 'code': '33', 'iso': 'FR / FRA', 'flag': '🇫🇷'},
    {'name': 'French Polynesia', 'code': '689', 'iso': 'PF / PYF', 'flag': '🇵🇫'},
    {'name': 'Gabon', 'code': '241', 'iso': 'GA / GAB', 'flag': '🇬🇦'},
    {'name': 'Gambia', 'code': '220', 'iso': 'GM / GMB', 'flag': '🇬🇲'},
    {'name': 'Georgia', 'code': '995', 'iso': 'GE / GEO', 'flag': '🇬🇪'},
    {'name': 'Germany', 'code': '49', 'iso': 'DE / DEU', 'flag': '🇩🇪'},
    {'name': 'Ghana', 'code': '233', 'iso': 'GH / GHA', 'flag': '🇬🇭'},
    {'name': 'Gibraltar', 'code': '350', 'iso': 'GI / GIB', 'flag': '🇬🇮'},
    {'name': 'Greece', 'code': '30', 'iso': 'GR / GRC', 'flag': '🇬🇷'},
    {'name': 'Greenland', 'code': '299', 'iso': 'GL / GRL', 'flag': '🇬🇱'},
    {'name': 'Grenada', 'code': '1', 'iso': 'GD / GRD', 'flag': '🇬🇩'},
    {'name': 'Guam', 'code': '1', 'iso': 'GU / GUM', 'flag': '🇬🇺'},
    {'name': 'Guatemala', 'code': '502', 'iso': 'GT / GTM', 'flag': '🇬🇹'},
    {'name': 'Guernsey', 'code': '44', 'iso': 'GG / GGY', 'flag': '🇬🇬'},
    {'name': 'Guinea', 'code': '224', 'iso': 'GN / GIN', 'flag': '🇬🇳'},
    {'name': 'Guinea-Bissau', 'code': '245', 'iso': 'GW / GNB', 'flag': '🇬🇼'},
    {'name': 'Guyana', 'code': '592', 'iso': 'GY / GUY', 'flag': '🇬🇾'},
    {'name': 'Haiti', 'code': '509', 'iso': 'HT / HTI', 'flag': '🇭🇹'},
    {'name': 'Honduras', 'code': '504', 'iso': 'HN / HND', 'flag': '🇭🇳'},
    {'name': 'Hong Kong', 'code': '852', 'iso': 'HK / HKG', 'flag': '🇭🇰'},
    {'name': 'Hungary', 'code': '36', 'iso': 'HU / HUN', 'flag': '🇭🇺'},
    {'name': 'Iceland', 'code': '354', 'iso': 'IS / ISL', 'flag': '🇮🇸'},
    {'name': 'India', 'code': '91', 'iso': 'IN / IND', 'flag': '🇮🇳'},
    {'name': 'Indonesia', 'code': '62', 'iso': 'ID / IDN', 'flag': '🇮🇩'},
    {'name': 'Iran', 'code': '98', 'iso': 'IR / IRN', 'flag': '🇮🇷'},
    {'name': 'Iraq', 'code': '964', 'iso': 'IQ / IRQ', 'flag': '🇮🇶'},
    {'name': 'Ireland', 'code': '353', 'iso': 'IE / IRL', 'flag': '🇮🇪'},
    {'name': 'Isle of Man', 'code': '44', 'iso': 'IM / IMN', 'flag': '🇮🇲'},
    {'name': 'Israel', 'code': '972', 'iso': 'IL / ISR', 'flag': '🇮🇱'},
    {'name': 'Italy', 'code': '39', 'iso': 'IT / ITA', 'flag': '🇮🇹'},
    {'name': 'Ivory Coast', 'code': '225', 'iso': 'CI / CIV', 'flag': '🇨🇮'},
    {'name': 'Jamaica', 'code': '1', 'iso': 'JM / JAM', 'flag': '🇯🇲'},
    {'name': 'Japan', 'code': '81', 'iso': 'JP / JPN', 'flag': '🇯🇵'},
    {'name': 'Jersey', 'code': '44', 'iso': 'JE / JEY', 'flag': '🇯🇪'},
    {'name': 'Jordan', 'code': '962', 'iso': 'JO / JOR', 'flag': '🇯🇴'},
    {'name': 'Kazakhstan', 'code': '7', 'iso': 'KZ / KAZ', 'flag': '🇰🇿'},
    {'name': 'Kenya', 'code': '254', 'iso': 'KE / KEN', 'flag': '🇰🇪'},
    {'name': 'Kiribati', 'code': '686', 'iso': 'KI / KIR', 'flag': '🇰🇮'},
    {'name': 'Kosovo', 'code': '383', 'iso': 'XK / XKX', 'flag': '🇽🇰'},
    {'name': 'Kuwait', 'code': '965', 'iso': 'KW / KWT', 'flag': '🇰🇼'},
    {'name': 'Kyrgyzstan', 'code': '996', 'iso': 'KG / KGZ', 'flag': '🇰🇬'},
    {'name': 'Laos', 'code': '856', 'iso': 'LA / LAO', 'flag': '🇱🇦'},
    {'name': 'Latvia', 'code': '371', 'iso': 'LV / LVA', 'flag': '🇱🇻'},
    {'name': 'Lebanon', 'code': '961', 'iso': 'LB / LBN', 'flag': '🇱🇧'},
    {'name': 'Lesotho', 'code': '266', 'iso': 'LS / LSO', 'flag': '🇱🇸'},
    {'name': 'Liberia', 'code': '231', 'iso': 'LR / LBR', 'flag': '🇱🇷'},
    {'name': 'Libya', 'code': '218', 'iso': 'LY / LBY', 'flag': '🇱🇾'},
    {'name': 'Liechtenstein', 'code': '423', 'iso': 'LI / LIE', 'flag': '🇱🇮'},
    {'name': 'Lithuania', 'code': '370', 'iso': 'LT / LTU', 'flag': '🇱🇹'},
    {'name': 'Luxembourg', 'code': '352', 'iso': 'LU / LUX', 'flag': '🇱🇺'},
    {'name': 'Macau', 'code': '853', 'iso': 'MO / MAC', 'flag': '🇲🇴'},
    {'name': 'Macedonia', 'code': '389', 'iso': 'MK / MKD', 'flag': '🇲🇰'},
    {'name': 'Madagascar', 'code': '261', 'iso': 'MG / MDG', 'flag': '🇲🇬'},
    {'name': 'Malawi', 'code': '265', 'iso': 'MW / MWI', 'flag': '🇲🇼'},
    {'name': 'Malaysia', 'code': '60', 'iso': 'MY / MYS', 'flag': '🇲🇾'},
    {'name': 'Maldives', 'code': '960', 'iso': 'MV / MDV', 'flag': '🇲🇻'},
    {'name': 'Mali', 'code': '223', 'iso': 'ML / MLI', 'flag': '🇲🇱'},
    {'name': 'Malta', 'code': '356', 'iso': 'MT / MLT', 'flag': '🇲🇹'},
    {'name': 'Marshall Islands', 'code': '692', 'iso': 'MH / MHL', 'flag': '🇲🇭'},
    {'name': 'Mauritania', 'code': '222', 'iso': 'MR / MRT', 'flag': '🇲🇷'},
    {'name': 'Mauritius', 'code': '230', 'iso': 'MU / MUS', 'flag': '🇲🇺'},
    {'name': 'Mayotte', 'code': '262', 'iso': 'YT / MYT', 'flag': '🇾🇹'},
    {'name': 'Mexico', 'code': '52', 'iso': 'MX / MEX', 'flag': '🇲🇽'},
    {'name': 'Micronesia', 'code': '691', 'iso': 'FM / FSM', 'flag': '🇫🇲'},
    {'name': 'Moldova', 'code': '373', 'iso': 'MD / MDA', 'flag': '🇲🇩'},
    {'name': 'Monaco', 'code': '377', 'iso': 'MC / MCO', 'flag': '🇲🇨'},
    {'name': 'Mongolia', 'code': '976', 'iso': 'MN / MNG', 'flag': '🇲🇳'},
    {'name': 'Montenegro', 'code': '382', 'iso': 'ME / MNE', 'flag': '🇲🇪'},
    {'name': 'Montserrat', 'code': '1', 'iso': 'MS / MSR', 'flag': '🇲🇸'},
    {'name': 'Morocco', 'code': '212', 'iso': 'MA / MAR', 'flag': '🇲🇦'},
    {'name': 'Mozambique', 'code': '258', 'iso': 'MZ / MOZ', 'flag': '🇲🇿'},
    {'name': 'Myanmar', 'code': '95', 'iso': 'MM / MMR', 'flag': '🇲🇲'},
    {'name': 'Namibia', 'code': '264', 'iso': 'NA / NAM', 'flag': '🇳🇦'},
    {'name': 'Nauru', 'code': '674', 'iso': 'NR / NRU', 'flag': '🇳🇷'},
    {'name': 'Nepal', 'code': '977', 'iso': 'NP / NPL', 'flag': '🇳🇵'},
    {'name': 'Netherlands', 'code': '31', 'iso': 'NL / NLD', 'flag': '🇳🇱'},
    {'name': 'Netherlands Antilles', 'code': '599', 'iso': 'AN / ANT', 'flag': '🇦🇳'},
    {'name': 'New Caledonia', 'code': '687', 'iso': 'NC / NCL', 'flag': '🇳🇨'},
    {'name': 'New Zealand', 'code': '64', 'iso': 'NZ / NZL', 'flag': '🇳🇿'},
    {'name': 'Nicaragua', 'code': '505', 'iso': 'NI / NIC', 'flag': '🇳🇮'},
    {'name': 'Niger', 'code': '227', 'iso': 'NE / NER', 'flag': '🇳🇪'},
    {'name': 'Nigeria', 'code': '234', 'iso': 'NG / NGA', 'flag': '🇳🇬'},
    {'name': 'Niue', 'code': '683', 'iso': 'NU / NIU', 'flag': '🇳🇺'},
    {'name': 'North Korea', 'code': '850', 'iso': 'KP / PRK', 'flag': '🇰🇵'},
    {'name': 'Northern Mariana Islands', 'code': '1', 'iso': 'MP / MNP', 'flag': '🇲🇵'},
    {'name': 'Norway', 'code': '47', 'iso': 'NO / NOR', 'flag': '🇳🇴'},
    {'name': 'Oman', 'code': '968', 'iso': 'OM / OMN', 'flag': '🇴🇲'},
    {'name': 'Pakistan', 'code': '92', 'iso': 'PK / PAK', 'flag': '🇵🇰'},
    {'name': 'Palau', 'code': '680', 'iso': 'PW / PLW', 'flag': '🇵🇼'},
    {'name': 'Palestine', 'code': '970', 'iso': 'PS / PSE', 'flag': '🇵🇸'},
    {'name': 'Panama', 'code': '507', 'iso': 'PA / PAN', 'flag': '🇵🇦'},
    {'name': 'Papua New Guinea', 'code': '675', 'iso': 'PG / PNG', 'flag': '🇵🇬'},
    {'name': 'Paraguay', 'code': '595', 'iso': 'PY / PRY', 'flag': '🇵🇾'},
    {'name': 'Peru', 'code': '51', 'iso': 'PE / PER', 'flag': '🇵🇪'},
    {'name': 'Philippines', 'code': '63', 'iso': 'PH / PHL', 'flag': '🇵🇭'},
    {'name': 'Pitcairn', 'code': '64', 'iso': 'PN / PCN', 'flag': '🇵🇳'},
    {'name': 'Poland', 'code': '48', 'iso': 'PL / POL', 'flag': '🇵🇱'},
    {'name': 'Portugal', 'code': '351', 'iso': 'PT / PRT', 'flag': '🇵🇹'},
    {'name': 'Puerto Rico', 'code': '1, 1', 'iso': 'PR / PRI', 'flag': '🇵🇷'},
    {'name': 'Qatar', 'code': '974', 'iso': 'QA / QAT', 'flag': '🇶🇦'},
    {'name': 'Republic of the Congo', 'code': '242', 'iso': 'CG / COG', 'flag': '🇨🇬'},
    {'name': 'Reunion', 'code': '262', 'iso': 'RE / REU', 'flag': '🇷🇪'},
    {'name': 'Romania', 'code': '40', 'iso': 'RO / ROU', 'flag': '🇷🇴'},
    {'name': 'Russia', 'code': '7', 'iso': 'RU / RUS', 'flag': '🇷🇺'},
    {'name': 'Rwanda', 'code': '250', 'iso': 'RW / RWA', 'flag': '🇷🇼'},
    {'name': 'Saint Barthelemy', 'code': '590', 'iso': 'BL / BLM', 'flag': '🇧🇱'},
    {'name': 'Saint Helena', 'code': '290', 'iso': 'SH / SHN', 'flag': '🇸🇭'},
    {'name': 'Saint Kitts and Nevis', 'code': '1', 'iso': 'KN / KNA', 'flag': '🇰🇳'},
    {'name': 'Saint Lucia', 'code': '1', 'iso': 'LC / LCA', 'flag': '🇱🇨'},
    {'name': 'Saint Martin', 'code': '590', 'iso': 'MF / MAF', 'flag': '🇲🇫'},
    {'name': 'Saint Pierre and Miquelon', 'code': '508', 'iso': 'PM / SPM', 'flag': '🇵🇲'},
    {'name': 'Saint Vincent and the Grenadines', 'code': '1', 'iso': 'VC / VCT', 'flag': '🇻🇨'},
    {'name': 'Samoa', 'code': '685', 'iso': 'WS / WSM', 'flag': '🇼🇸'},
    {'name': 'San Marino', 'code': '378', 'iso': 'SM / SMR', 'flag': '🇸🇲'},
    {'name': 'Sao Tome and Principe', 'code': '239', 'iso': 'ST / STP', 'flag': '🇸🇹'},
    {'name': 'Saudi Arabia', 'code': '966', 'iso': 'SA / SAU', 'flag': '🇸🇦'},
    {'name': 'Senegal', 'code': '221', 'iso': 'SN / SEN', 'flag': '🇸🇳'},
    {'name': 'Serbia', 'code': '381', 'iso': 'RS / SRB', 'flag': '🇷🇸'},
    {'name': 'Seychelles', 'code': '248', 'iso': 'SC / SYC', 'flag': '🇸🇨'},
    {'name': 'Sierra Leone', 'code': '232', 'iso': 'SL / SLE', 'flag': '🇸🇱'},
    {'name': 'Singapore', 'code': '65', 'iso': 'SG / SGP', 'flag': '🇸🇬'},
    {'name': 'Sint Maarten', 'code': '1', 'iso': 'SX / SXM', 'flag': '🇸🇽'},
    {'name': 'Slovakia', 'code': '421', 'iso': 'SK / SVK', 'flag': '🇸🇰'},
    {'name': 'Slovenia', 'code': '386', 'iso': 'SI / SVN', 'flag': '🇸🇮'},
    {'name': 'Solomon Islands', 'code': '677', 'iso': 'SB / SLB', 'flag': '🇸🇧'},
    {'name': 'Somalia', 'code': '252', 'iso': 'SO / SOM', 'flag': '🇸🇴'},
    {'name': 'South Africa', 'code': '27', 'iso': 'ZA / ZAF', 'flag': '🇿🇦'},
    {'name': 'South Korea', 'code': '82', 'iso': 'KR / KOR', 'flag': '🇰🇷'},
    {'name': 'South Sudan', 'code': '211', 'iso': 'SS / SSD', 'flag': '🇸🇸'},
    {'name': 'Spain', 'code': '34', 'iso': 'ES / ESP', 'flag': '🇪🇸'},
    {'name': 'Sri Lanka', 'code': '94', 'iso': 'LK / LKA', 'flag': '🇱🇰'},
    {'name': 'Sudan', 'code': '249', 'iso': 'SD / SDN', 'flag': '🇸🇩'},
    {'name': 'Suriname', 'code': '597', 'iso': 'SR / SUR', 'flag': '🇸🇷'},
    {'name': 'Svalbard and Jan Mayen', 'code': '47', 'iso': 'SJ / SJM', 'flag': '🇸🇯'},
    {'name': 'Swaziland', 'code': '268', 'iso': 'SZ / SWZ', 'flag': '🇸🇿'},
    {'name': 'Sweden', 'code': '46', 'iso': 'SE / SWE', 'flag': '🇸🇪'},
    {'name': 'Switzerland', 'code': '41', 'iso': 'CH / CHE', 'flag': '🇨🇭'},
    {'name': 'Syria', 'code': '963', 'iso': 'SY / SYR', 'flag': '🇸🇾'},
    {'name': 'Taiwan', 'code': '886', 'iso': 'TW / TWN', 'flag': '🇹🇼'},
    {'name': 'Tajikistan', 'code': '992', 'iso': 'TJ / TJK', 'flag': '🇹🇯'},
    {'name': 'Tanzania', 'code': '255', 'iso': 'TZ / TZA', 'flag': '🇹🇿'},
    {'name': 'Thailand', 'code': '66', 'iso': 'TH / THA', 'flag': '🇹🇭'},
    {'name': 'Togo', 'code': '228', 'iso': 'TG / TGO', 'flag': '🇹🇬'},
    {'name': 'Tokelau', 'code': '690', 'iso': 'TK / TKL', 'flag': '🇹🇰'},
    {'name': 'Tonga', 'code': '676', 'iso': 'TO / TON', 'flag': '🇹🇴'},
    {'name': 'Trinidad and Tobago', 'code': '1', 'iso': 'TT / TTO', 'flag': '🇹🇹'},
    {'name': 'Tunisia', 'code': '216', 'iso': 'TN / TUN', 'flag': '🇹🇳'},
    {'name': 'Turkey', 'code': '90', 'iso': 'TR / TUR', 'flag': '🇹🇷'},
    {'name': 'Turkmenistan', 'code': '993', 'iso': 'TM / TKM', 'flag': '🇹🇲'},
    {'name': 'Turks and Caicos Islands', 'code': '1', 'iso': 'TC / TCA', 'flag': '🇹🇨'},
    {'name': 'Tuvalu', 'code': '688', 'iso': 'TV / TUV', 'flag': '🇹🇻'},
    {'name': 'U.S. Virgin Islands', 'code': '1', 'iso': 'VI / VIR', 'flag': "🇻🇬"},
    {'name': 'Uganda', 'code': '256', 'iso': 'UG / UGA', 'flag': '🇺🇬'},
    {'name': 'Ukraine', 'code': '380', 'iso': 'UA / UKR', 'flag': '🇺🇦'},
    {'name': 'United Arab Emirates', 'code': '971', 'iso': 'AE / ARE', 'flag': '🇦🇪'},
    {'name': 'United Kingdom', 'code': '44', 'iso': 'GB / GBR', 'flag': '🇬🇧'},
    {'name': 'United States', 'code': '1', 'iso': 'US / USA', 'flag': '🇺🇸'},
    {'name': 'Uruguay', 'code': '598', 'iso': 'UY / URY', 'flag': '🇺🇾'},
    {'name': 'Uzbekistan', 'code': '998', 'iso': 'UZ / UZB', 'flag': '🇺🇿'},
    {'name': 'Vanuatu', 'code': '678', 'iso': 'VU / VUT', 'flag': '🇻🇺'},
    {'name': 'Vatican', 'code': '379', 'iso': 'VA / VAT', 'flag': '🇻🇦'},
    {'name': 'Venezuela', 'code': '58', 'iso': 'VE / VEN', 'flag': '🇻🇪'},
    {'name': 'Vietnam', 'code': '84', 'iso': 'VN / VNM','flag':"🇻🇳"},
    {'name': 'Wallis and Futuna', 'code': '681', 'iso': 'WF / WLF', 'flag': '🇼🇫'},
    {'name': 'Western Sahara', 'code': '212', 'iso': 'EH / ESH', 'flag': '🇪🇭'},
    {'name': 'Yemen', 'code': '967', 'iso': 'YE / YEM', 'flag': '🇾🇪'},
    {'name': 'Zambia', 'code': '260', 'iso': 'ZM / ZMB', 'flag': '🇿🇲'},
    {'name': 'Zimbabwe', 'code': '263', 'iso': 'ZW / ZWE', 'flag': '🇿🇼'}
]