from typing import Optional, List

from pydantic import BaseModel


class CompletionUsage(BaseModel):
    completion_tokens: Optional[int] = None
    """Number of tokens in the generated completion."""

    prompt_tokens: Optional[int] = None
    """Number of tokens in the prompt."""

    total_tokens: Optional[int] = None
    """Total number of tokens used in the request (prompt + completion)."""


class ChatCompletionMessage(BaseModel):
    content: Optional[str] = None
    """The contents of the message."""

    role: Optional[str] = None
    """The role of the author of this message."""


class Choice(BaseModel):
    finish_reason: Optional[str] = None
    """The reason the model stopped generating tokens.
    
    Literal["stop", "length", "tool_calls", "content_filter", "function_call"]
    This will be `stop` if the model hit a natural stop point or a provided stop
    sequence, `length` if the maximum number of tokens specified in the request was
    reached, `content_filter` if content was omitted due to a flag from our content
    filters, `tool_calls` if the model called a tool, or `function_call`
    (deprecated) if the model called a function.
    """

    index: Optional[int] = None
    """The index of the choice in the list of choices."""

    message:  Optional[ChatCompletionMessage] = None
    """A chat completion message generated by the model."""


class ChatCompletion(BaseModel):
    id: Optional[str] = None
    """A unique identifier for the chat completion."""

    choices: List[Choice]
    """A list of chat completion choices.

    Can be more than one if `n` is greater than 1.
    """

    created: Optional[int] = None
    """The Unix timestamp (in seconds) of when the chat completion was created."""

    model: Optional[str] = None
    """The model used for the chat completion."""

    object: Optional[str] = None
    """The object type, which is always `chat.completion`."""

    usage: Optional[CompletionUsage] = None
    """Usage statistics for the completion request."""
