from .seiRJ import pesquisar_processo, baixar_documentos, procurar_documentos,obter_processos_bloco,entrar_e_obter_processos_bloco,inserir_hyperlink_sei, incluir_processo_bloco,remover_processo_bloco
from .seiRJ import login_sei,criar_processo,buscar_numero_documento,incluir_bloco_assinatura,gerar_documento_externo,gerar_despacho, escrever_acompanhamento_especial,limpar_anotacao, escrever_anotacao,buscar_informacao_em_documento
from .siafeRIO import login_siafe

