from setuptools import setup, find_packages

setup(
    name='lbdc',
    version='0.0.3',
    description='compile `λ~.` -> `lambda ~ : `',
    author='du7ec',
    author_email='dutec6834@gmail.com',
    url='https://github.com/FarAway6834/lbdc',
    packages=find_packages(exclude=[]),
    keywords=['lbdc', 'λ', 'lambda', 'calculate', 'compiler'],
    python_requires='>=3.0',
    package_data={},
    classifiers=[
        'Programming Language :: Python :: 3.0',
        'Programming Language :: Python :: 3.1',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Programming Language :: Python :: 3.14',
    ],
)
