
#
# ===== Note =====
#
# This library was auto-generated by AG Remap's APIMirrorBuilder tool,
#   a build system tool used in AG Remap's CI pipeline that creates a mirror for the existing
#   API source code since we cannot rename the original name of 'FixRaidenBoss2' to 'Anime Game Remap' in Pypi,
#   therefore, we decided to make a brand new package that mirrors the original API.
#
# ***** APIMirrorBuilder Stats *****
#
# Version: 1.0.0
# Authors: Albert Gold#2696
# Datetime Ran: Monday, February 24, 2025 07:21:50.649 PM UTC
# Run Hash: c46df54b-39af-4637-93ce-a0a23a8c789a
# 
# **********************************
# ================
#

# ===== Anime Game Remap (AG Remap) =====
# Authors: Albert Gold#2696, NK#1321
#
# if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
# Special Thanks:
#   nguen#2011 (for support)
#   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
#   HazrateGolabi#1364 (for being awesome, and improving the code)

#
# ***** AG Remap Stats *****
#
# Version: 4.2.7
# Authors: Albert Gold#2696, NK#1321
# Datetime Compiled: Monday, February 24, 2025 07:21:50.649 PM UTC
# Build Hash: 0ebb48e8-40b8-4613-81d0-410cfd8593cd
#
# **************************
#

from FixRaidenBoss2 import remapMain

if __name__ == '__main__':
    remapMain()