# Generated by Django 4.2.17 on 2025-02-19 21:10

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bothelpers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
