
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-24T11:09:39-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a74dbe1add49c8a22f303fbe8f264a68c795effe",
 "version": "v0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
