from typing import Tuple

def generate_p_g(bits: int) -> Tuple[str, int]: ...
def generate_a_or_b(p: str) -> str: ...
def generate_A_or_B(p: str, g: int, private_key: str) -> str: ...
def generate_shared_key(public_key: str, p: str, private_key: str) -> str: ...
