# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dima_sdk.models.get_people_list200_response_data_inner_direct_reports_inner import GetPeopleList200ResponseDataInnerDirectReportsInner

class TestGetPeopleList200ResponseDataInnerDirectReportsInner(unittest.TestCase):
    """GetPeopleList200ResponseDataInnerDirectReportsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPeopleList200ResponseDataInnerDirectReportsInner:
        """Test GetPeopleList200ResponseDataInnerDirectReportsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPeopleList200ResponseDataInnerDirectReportsInner`
        """
        model = GetPeopleList200ResponseDataInnerDirectReportsInner()
        if include_optional:
            return GetPeopleList200ResponseDataInnerDirectReportsInner(
                id = '642b0547-9d80-4d35-a085-fd977ef209ef',
                last_name = 'John',
                first_name = 'Doe',
                work_email = 'john.doe@example.com'
            )
        else:
            return GetPeopleList200ResponseDataInnerDirectReportsInner(
        )
        """

    def testGetPeopleList200ResponseDataInnerDirectReportsInner(self):
        """Test GetPeopleList200ResponseDataInnerDirectReportsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
