# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: momotor/rpc/proto/priority.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n momotor/rpc/proto/priority.proto\x12\x11momotor.rpc.proto*T\n\x08Priority\x12\n\n\x06NORMAL\x10\x00\x12\x13\n\x06LOWEST\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x10\n\x03LOW\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x08\n\x04HIGH\x10\x01\x12\x0b\n\x07HIGHEST\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'momotor.rpc.proto.priority_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRIORITY']._serialized_start=55
  _globals['_PRIORITY']._serialized_end=139
# @@protoc_insertion_point(module_scope)
