#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class ProtocolCompatibleRequest(object):
    """
    Attributes:
     - clientProtocolVersion
     - clientDescription
    """


    def __init__(self, clientProtocolVersion=None, clientDescription=None,):
        self.clientProtocolVersion = clientProtocolVersion
        self.clientDescription = clientDescription

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.clientProtocolVersion = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.clientDescription = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('ProtocolCompatibleRequest')
        if self.clientProtocolVersion is not None:
            oprot.writeFieldBegin('clientProtocolVersion', TType.I32, 1)
            oprot.writeI32(self.clientProtocolVersion)
            oprot.writeFieldEnd()
        if self.clientDescription is not None:
            oprot.writeFieldBegin('clientDescription', TType.STRING, 2)
            oprot.writeString(self.clientDescription.encode('utf-8') if sys.version_info[0] == 2 else self.clientDescription)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.clientProtocolVersion is None:
            raise TProtocolException(message='Required field clientProtocolVersion is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(ProtocolCompatibleRequest)
ProtocolCompatibleRequest.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'clientProtocolVersion', None, None, ),  # 1
    (2, TType.STRING, 'clientDescription', 'UTF8', None, ),  # 2
)
fix_spec(all_structs)
del all_structs
