"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import frogml_proto.jfml.model_version.v1.model_repository_spec_pb2
import frogml_proto.jfml.model_version.v1.model_version_framework_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ModelVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODEL_VERSION_ID_FIELD_NUMBER: builtins.int
    SPEC_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    CREATED_BY_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    model_version_id: builtins.str
    @property
    def spec(self) -> global___ModelVersionSpec: ...
    @property
    def status(self) -> global___ModelVersionStatus: ...
    created_by: builtins.str
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        model_version_id: builtins.str = ...,
        spec: global___ModelVersionSpec | None = ...,
        status: global___ModelVersionStatus | None = ...,
        created_by: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "spec", b"spec", "status", b"status", "updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "created_by", b"created_by", "model_version_id", b"model_version_id", "spec", b"spec", "status", b"status", "updated_at", b"updated_at"]) -> None: ...

global___ModelVersion = ModelVersion

class ModelVersionSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPOSITORY_SPEC_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    FRAMEWORK_FIELD_NUMBER: builtins.int
    PYTHON_VERSION_FIELD_NUMBER: builtins.int
    @property
    def repository_spec(self) -> frogml_proto.jfml.model_version.v1.model_repository_spec_pb2.ModelRepositorySpec:
        """Model Version's Repository's Spec"""
    name: builtins.str
    """Model Version's name"""
    @property
    def framework(self) -> frogml_proto.jfml.model_version.v1.model_version_framework_pb2.ModelVersionFramework: ...
    python_version: builtins.str
    """The Python version used when training the model"""
    def __init__(
        self,
        *,
        repository_spec: frogml_proto.jfml.model_version.v1.model_repository_spec_pb2.ModelRepositorySpec | None = ...,
        name: builtins.str = ...,
        framework: frogml_proto.jfml.model_version.v1.model_version_framework_pb2.ModelVersionFramework | None = ...,
        python_version: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["framework", b"framework", "repository_spec", b"repository_spec"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["framework", b"framework", "name", b"name", "python_version", b"python_version", "repository_spec", b"repository_spec"]) -> None: ...

global___ModelVersionSpec = ModelVersionSpec

class ModelVersionStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IN_PROGRESS_FIELD_NUMBER: builtins.int
    COMPLETED_FIELD_NUMBER: builtins.int
    FAILED_FIELD_NUMBER: builtins.int
    @property
    def in_progress(self) -> global___ModelVersionInProgressStatus: ...
    @property
    def completed(self) -> global___ModelVersionCompletedStatus: ...
    @property
    def failed(self) -> global___ModelVersionFailedStatus: ...
    def __init__(
        self,
        *,
        in_progress: global___ModelVersionInProgressStatus | None = ...,
        completed: global___ModelVersionCompletedStatus | None = ...,
        failed: global___ModelVersionFailedStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["completed", b"completed", "failed", b"failed", "in_progress", b"in_progress", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["completed", b"completed", "failed", b"failed", "in_progress", b"in_progress", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["status", b"status"]) -> typing_extensions.Literal["in_progress", "completed", "failed"] | None: ...

global___ModelVersionStatus = ModelVersionStatus

class ModelVersionInProgressStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ModelVersionInProgressStatus = ModelVersionInProgressStatus

class ModelVersionCompletedStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ModelVersionCompletedStatus = ModelVersionCompletedStatus

class ModelVersionFailedStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ModelVersionFailedStatus = ModelVersionFailedStatus
