
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-22T00:10:55+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2004d49ddeda17dc6404473b1f25f8769911e18",
 "version": "1.3.0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
