__title__ = "dask-trino"
__description__ = "dask integration for trino"
__url__ = "https://github.com/posulliv/dask-trino"
__version__ = "0.2.0"
__author__ = "Padraig O'Sullivan"
__author_email__ = "padraig.osullivan@starburstdata.com"
__license__ = "Apache 2.0"
