//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "component_capabilities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::component_type_capabilities::Entity")]
    ComponentTypeCapabilities,
}

impl Related<super::component_type_capabilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ComponentTypeCapabilities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
