//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "games_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub status: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::game_participants_history::Entity")]
    GameParticipantsHistory,
    #[sea_orm(has_many = "super::games_state_history::Entity")]
    GamesStateHistory,
}

impl Related<super::game_participants_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameParticipantsHistory.def()
    }
}

impl Related<super::games_state_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GamesStateHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
