//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "games_state_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub game_id: String,
    pub edit_type: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub edit_data: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::games_history::Entity",
        from = "Column::GameId",
        to = "super::games_history::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GamesHistory,
}

impl Related<super::games_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GamesHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
