//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "units")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uuid: String,
    pub name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::game_participants::Entity")]
    GameParticipants,
    #[sea_orm(has_many = "super::unit_components::Entity")]
    UnitComponents,
    #[sea_orm(has_many = "super::unit_owners::Entity")]
    UnitOwners,
    #[sea_orm(has_many = "super::user_configurations::Entity")]
    UserConfigurations,
}

impl Related<super::game_participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameParticipants.def()
    }
}

impl Related<super::unit_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnitComponents.def()
    }
}

impl Related<super::unit_owners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnitOwners.def()
    }
}

impl Related<super::user_configurations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConfigurations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::unit_owners::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::unit_owners::Relation::Units.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
