//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "unit_components")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub unit_id: i32,
    pub component_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::units::Entity",
        from = "Column::UnitId",
        to = "super::units::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Units,
    #[sea_orm(
        belongs_to = "super::user_components::Entity",
        from = "Column::ComponentId",
        to = "super::user_components::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    UserComponents,
}

impl Related<super::units::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Units.def()
    }
}

impl Related<super::user_components::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserComponents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
