import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_4f1667ffbb(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_444dcaf7f0():spartaqube_cli.list()
@app.command()
def sparta_0005b0a8d4():spartaqube_cli.sparta_0005b0a8d4()
@app.command()
def sparta_8a2de79695():print('Hello world!')
if __name__=='__main__':app()