# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from dima_sdk.models.get_people_list200_response_data_inner_addresses_inner import GetPeopleList200ResponseDataInnerAddressesInner
from dima_sdk.models.get_people_list200_response_data_inner_department import GetPeopleList200ResponseDataInnerDepartment
from dima_sdk.models.get_people_list200_response_data_inner_direct_manager import GetPeopleList200ResponseDataInnerDirectManager
from dima_sdk.models.get_people_list200_response_data_inner_direct_reports_inner import GetPeopleList200ResponseDataInnerDirectReportsInner
from dima_sdk.models.get_people_list200_response_data_inner_emails_inner import GetPeopleList200ResponseDataInnerEmailsInner
from dima_sdk.models.get_people_list200_response_data_inner_employments_inner import GetPeopleList200ResponseDataInnerEmploymentsInner
from dima_sdk.models.get_people_list200_response_data_inner_employments_inner_client_legal_entity import GetPeopleList200ResponseDataInnerEmploymentsInnerClientLegalEntity
from typing import Optional, Set
from typing_extensions import Self

class GetPeopleList200ResponseDataInner(BaseModel):
    """
    GetPeopleList200ResponseDataInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier for the employee.")
    state: Optional[StrictStr] = Field(default=None, description="The state of the employee.")
    emails: Optional[List[GetPeopleList200ResponseDataInnerEmailsInner]] = Field(default=None, description="An array of the employee's email addresses.")
    country: Optional[StrictStr] = Field(default=None, description="The country of the employee.")
    timezone: Optional[StrictStr] = Field(default=None, description="The timezone of the employee.")
    addresses: Optional[List[GetPeopleList200ResponseDataInnerAddressesInner]] = None
    full_name: Optional[StrictStr] = Field(default=None, description="The full name of the employee.")
    job_title: Optional[StrictStr] = Field(default=None, description="The job title of the employee.")
    last_name: Optional[StrictStr] = Field(default=None, description="The last name of the employee.")
    seniority: Optional[StrictStr] = Field(default=None, description="The seniority level of the employee.")
    worker_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The worker ID of the employee.")
    birth_date: Optional[StrictStr] = Field(default=None, description="The birth date of the employee.")
    created_at: Optional[datetime] = Field(default=None, description="The creation timestamp of the employee record.")
    department: Optional[GetPeopleList200ResponseDataInnerDepartment] = None
    first_name: Optional[StrictStr] = Field(default=None, description="The first name of the employee.")
    start_date: Optional[date] = Field(default=None, description="The date the employee started working.")
    updated_at: Optional[datetime] = Field(default=None, description="Long date-time format following ISO-8601")
    employments: Optional[List[GetPeopleList200ResponseDataInnerEmploymentsInner]] = None
    external_id: Optional[StrictStr] = Field(default=None, description="The external ID of the employee.")
    hiring_type: Optional[StrictStr] = Field(default=None, description="The type of hiring of the employee.")
    hiring_status: Optional[StrictStr] = Field(default=None, description="The current hiring status of the employee.")
    nationalities: Optional[List[StrictStr]] = Field(default=None, description="The nationality of the employee.")
    work_location: Optional[StrictStr] = Field(default=None, description="The work location of the employee.")
    direct_manager: Optional[GetPeopleList200ResponseDataInnerDirectManager] = None
    direct_reports: Optional[List[GetPeopleList200ResponseDataInnerDirectReportsInner]] = Field(default=None, description="The direct reports to the employee.")
    completion_date: Optional[StrictStr] = Field(default=None, description="The completion date of the task or project.")
    new_hiring_status: Optional[StrictStr] = Field(default=None, description="The new hiring status of the employee.")
    client_legal_entity: Optional[GetPeopleList200ResponseDataInnerEmploymentsInnerClientLegalEntity] = None
    preferred_last_name: Optional[StrictStr] = Field(default=None, description="The preferred last name of the employee.")
    direct_reports_count: Optional[StrictInt] = Field(default=None, description="The count of direct reports to the employee.")
    preferred_first_name: Optional[StrictStr] = Field(default=None, description="The preferred first name of the employee.")
    direct_employee_termination_last_day: Optional[datetime] = Field(default=None, description="The last day of work mentioned on the primary contract termination.")
    __properties: ClassVar[List[str]] = ["id", "state", "emails", "country", "timezone", "addresses", "full_name", "job_title", "last_name", "seniority", "worker_id", "birth_date", "created_at", "department", "first_name", "start_date", "updated_at", "employments", "external_id", "hiring_type", "hiring_status", "nationalities", "work_location", "direct_manager", "direct_reports", "completion_date", "new_hiring_status", "client_legal_entity", "preferred_last_name", "direct_reports_count", "preferred_first_name", "direct_employee_termination_last_day"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetPeopleList200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in emails (list)
        _items = []
        if self.emails:
            for _item_emails in self.emails:
                if _item_emails:
                    _items.append(_item_emails.to_dict())
            _dict['emails'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in addresses (list)
        _items = []
        if self.addresses:
            for _item_addresses in self.addresses:
                if _item_addresses:
                    _items.append(_item_addresses.to_dict())
            _dict['addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of department
        if self.department:
            _dict['department'] = self.department.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in employments (list)
        _items = []
        if self.employments:
            for _item_employments in self.employments:
                if _item_employments:
                    _items.append(_item_employments.to_dict())
            _dict['employments'] = _items
        # override the default output from pydantic by calling `to_dict()` of direct_manager
        if self.direct_manager:
            _dict['direct_manager'] = self.direct_manager.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in direct_reports (list)
        _items = []
        if self.direct_reports:
            for _item_direct_reports in self.direct_reports:
                if _item_direct_reports:
                    _items.append(_item_direct_reports.to_dict())
            _dict['direct_reports'] = _items
        # override the default output from pydantic by calling `to_dict()` of client_legal_entity
        if self.client_legal_entity:
            _dict['client_legal_entity'] = self.client_legal_entity.to_dict()
        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if completion_date (nullable) is None
        # and model_fields_set contains the field
        if self.completion_date is None and "completion_date" in self.model_fields_set:
            _dict['completion_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetPeopleList200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "state": obj.get("state"),
            "emails": [GetPeopleList200ResponseDataInnerEmailsInner.from_dict(_item) for _item in obj["emails"]] if obj.get("emails") is not None else None,
            "country": obj.get("country"),
            "timezone": obj.get("timezone"),
            "addresses": [GetPeopleList200ResponseDataInnerAddressesInner.from_dict(_item) for _item in obj["addresses"]] if obj.get("addresses") is not None else None,
            "full_name": obj.get("full_name"),
            "job_title": obj.get("job_title"),
            "last_name": obj.get("last_name"),
            "seniority": obj.get("seniority"),
            "worker_id": obj.get("worker_id"),
            "birth_date": obj.get("birth_date"),
            "created_at": obj.get("created_at"),
            "department": GetPeopleList200ResponseDataInnerDepartment.from_dict(obj["department"]) if obj.get("department") is not None else None,
            "first_name": obj.get("first_name"),
            "start_date": obj.get("start_date"),
            "updated_at": obj.get("updated_at"),
            "employments": [GetPeopleList200ResponseDataInnerEmploymentsInner.from_dict(_item) for _item in obj["employments"]] if obj.get("employments") is not None else None,
            "external_id": obj.get("external_id"),
            "hiring_type": obj.get("hiring_type"),
            "hiring_status": obj.get("hiring_status"),
            "nationalities": obj.get("nationalities"),
            "work_location": obj.get("work_location"),
            "direct_manager": GetPeopleList200ResponseDataInnerDirectManager.from_dict(obj["direct_manager"]) if obj.get("direct_manager") is not None else None,
            "direct_reports": [GetPeopleList200ResponseDataInnerDirectReportsInner.from_dict(_item) for _item in obj["direct_reports"]] if obj.get("direct_reports") is not None else None,
            "completion_date": obj.get("completion_date"),
            "new_hiring_status": obj.get("new_hiring_status"),
            "client_legal_entity": GetPeopleList200ResponseDataInnerEmploymentsInnerClientLegalEntity.from_dict(obj["client_legal_entity"]) if obj.get("client_legal_entity") is not None else None,
            "preferred_last_name": obj.get("preferred_last_name"),
            "direct_reports_count": obj.get("direct_reports_count"),
            "preferred_first_name": obj.get("preferred_first_name"),
            "direct_employee_termination_last_day": obj.get("direct_employee_termination_last_day")
        })
        return _obj


