import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_02a4f57b4b(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_300429d16b():spartaqube_cli.list()
@app.command()
def sparta_20d6ffa3bd():spartaqube_cli.sparta_20d6ffa3bd()
@app.command()
def sparta_845fce7653():print('Hello world!')
if __name__=='__main__':app()