from .hospitalResidentsProblem import HospitalResidentsProblem
from .stableMarriageProblem import StableMarriageProblem
from .studentProjectAllocation import StudentProjectAllocation
from .studentProjectAllocationProjects import StudentProjectAllocationProjectsSingle
from .studentProjectAllocationProjects import StudentProjectAllocationProjectsMultiple

from .hospitalResidentsProblem import HospitalResidentsProblem as HR
from .stableMarriageProblem import StableMarriageProblem as SM
from .studentProjectAllocation import StudentProjectAllocation as SPAS
from .studentProjectAllocationProjects import StudentProjectAllocationProjectsSingle as SPAP_Single
from .studentProjectAllocationProjects import StudentProjectAllocationProjectsMultiple as SPAP_Multiple
from .studentProjectAllocationProjects import utils as SPAP_utils