from datetime import datetime
from typing import Any, Dict, List, Optional, TypedDict


class Action(TypedDict):
    taskDefinitionPropertiesId: Optional[int]
    appTasksMetadata: Optional[Any]
    actionLabel: Optional[str]
    status: Optional[str]
    data: Optional[Dict[str, Any]]
    action: Optional[str]
    waitJobState: Optional[str]
    organizationUnitFullyQualifiedName: Optional[str]
    tags: Optional[List[Any]]
    assignedToUser: Optional[Any]
    taskSlaDetails: Optional[List[Any]]
    completedByUser: Optional[Any]
    taskAssignmentCriteria: Optional[str]
    taskAssignees: Optional[List[Any]]
    title: Optional[str]
    type: Optional[str]
    priority: Optional[str]
    assignedToUserId: Optional[int]
    organizationUnitId: Optional[int]
    externalTag: Optional[str]
    creatorJobKey: Optional[str]
    waitJobKey: Optional[str]
    lastAssignedTime: Optional[datetime]
    completionTime: Optional[datetime]
    parentOperationId: Optional[str]
    key: Optional[str]
    isDeleted: Optional[bool]
    deleterUserId: Optional[int]
    deletionTime: Optional[datetime]
    lastModificationTime: Optional[datetime]
    lastModifierUserId: Optional[int]
    creationTime: Optional[datetime]
    creatorUserId: Optional[int]
    id: Optional[int]
