# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deel_sdk.api.contracts_api import ContractsApi


class TestContractsApi(unittest.TestCase):
    """ContractsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContractsApi()

    def tearDown(self) -> None:
        pass

    def test_get_contract_list(self) -> None:
        """Test case for get_contract_list

        List of contracts
        """
        pass


if __name__ == '__main__':
    unittest.main()
