# coding: utf-8

"""
    Deel REST API

    Deel REST API

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deel_sdk.models.get_contract_list200_response_data_inner_signatures import GetContractList200ResponseDataInnerSignatures

class TestGetContractList200ResponseDataInnerSignatures(unittest.TestCase):
    """GetContractList200ResponseDataInnerSignatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetContractList200ResponseDataInnerSignatures:
        """Test GetContractList200ResponseDataInnerSignatures
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetContractList200ResponseDataInnerSignatures`
        """
        model = GetContractList200ResponseDataInnerSignatures()
        if include_optional:
            return GetContractList200ResponseDataInnerSignatures(
                client_signed_at = '2019-03-21T13:45:07.515Z',
                worker_signature = 'John Doe',
                worker_signed_at = '2019-03-21T13:45:07.515Z'
            )
        else:
            return GetContractList200ResponseDataInnerSignatures(
                client_signed_at = '2019-03-21T13:45:07.515Z',
                worker_signature = 'John Doe',
                worker_signed_at = '2019-03-21T13:45:07.515Z',
        )
        """

    def testGetContractList200ResponseDataInnerSignatures(self):
        """Test GetContractList200ResponseDataInnerSignatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
